from __future__ import annotations

import builtins
from typing import Protocol
from uuid import UUID

from wandermind.models import (
    Candidate,
    Feedback,
    KnowledgeEdge,
    KnowledgeItem,
    Seed,
    WanderSession,
    Wonder,
)
from wandermind.runtime.base import RuntimeSession


class KnowledgeRepository(Protocol):
    async def create(self, item: KnowledgeItem) -> KnowledgeItem: ...
    async def get(self, item_id: UUID) -> KnowledgeItem | None: ...
    async def update(self, item: KnowledgeItem) -> KnowledgeItem: ...
    async def delete(self, item_id: UUID) -> bool: ...
    async def list(self, *, offset: int = 0, limit: int = 50) -> builtins.list[KnowledgeItem]: ...
    async def search(self, query: str, *, limit: int = 20) -> builtins.list[KnowledgeItem]: ...


class GraphRepository(Protocol):
    async def create(self, edge: KnowledgeEdge) -> KnowledgeEdge: ...
    async def list_for_item(self, item_id: UUID) -> builtins.list[KnowledgeEdge]: ...
    async def delete(self, edge_id: UUID) -> bool: ...


class SeedRepository(Protocol):
    async def create(self, seed: Seed) -> Seed: ...
    async def get(self, seed_id: UUID) -> Seed | None: ...
    async def update(self, seed: Seed) -> Seed: ...
    async def list(self, *, offset: int = 0, limit: int = 50) -> builtins.list[Seed]: ...


class CandidateRepository(Protocol):
    async def create(self, candidate: Candidate) -> Candidate: ...
    async def get(self, candidate_id: UUID) -> Candidate | None: ...
    async def update(self, candidate: Candidate) -> Candidate: ...
    async def delete(self, candidate_id: UUID) -> bool: ...
    async def list(self, *, offset: int = 0, limit: int = 50) -> builtins.list[Candidate]: ...
    async def list_for_session(self, session_id: UUID) -> builtins.list[Candidate]: ...


class WonderRepository(Protocol):
    async def create(self, wonder: Wonder) -> Wonder: ...
    async def get(self, wonder_id: UUID) -> Wonder | None: ...
    async def update(self, wonder: Wonder) -> Wonder: ...
    async def delete(self, wonder_id: UUID) -> bool: ...
    async def list(self, *, offset: int = 0, limit: int = 50) -> builtins.list[Wonder]: ...
    async def search_similar(self, text: str, *, limit: int = 20) -> builtins.list[Wonder]: ...


class SessionRepository(Protocol):
    async def create(self, session: WanderSession) -> WanderSession: ...
    async def get(self, session_id: UUID) -> WanderSession | None: ...
    async def update(self, session: WanderSession) -> WanderSession: ...
    async def delete(self, session_id: UUID) -> bool: ...
    async def list(self, *, offset: int = 0, limit: int = 50) -> builtins.list[WanderSession]: ...


class FeedbackRepository(Protocol):
    async def create(self, feedback: Feedback) -> Feedback: ...
    async def get(self, feedback_id: UUID) -> Feedback | None: ...
    async def delete(self, feedback_id: UUID) -> bool: ...
    async def list_for_wonder(self, wonder_id: UUID) -> builtins.list[Feedback]: ...


class RuntimeSessionRepository(Protocol):
    async def create(self, session: RuntimeSession) -> RuntimeSession: ...
    async def get(self, session_id: UUID) -> RuntimeSession | None: ...
    async def update(self, session: RuntimeSession) -> RuntimeSession: ...
    async def list(self, *, offset: int = 0, limit: int = 50) -> builtins.list[RuntimeSession]: ...


class RepositoryBundle(Protocol):
    @property
    def knowledge(self) -> KnowledgeRepository: ...

    @property
    def graph(self) -> GraphRepository: ...

    @property
    def seeds(self) -> SeedRepository: ...

    @property
    def candidates(self) -> CandidateRepository: ...

    @property
    def wonders(self) -> WonderRepository: ...

    @property
    def sessions(self) -> SessionRepository: ...

    @property
    def feedback(self) -> FeedbackRepository: ...

    @property
    def runtime_sessions(self) -> RuntimeSessionRepository: ...
